### ISSUE TITLE
Leaking Globals

### ISSUE THREAD

**Issue by Azilroka** [solagegrey/ElvUI_ItemCount#2]
You leak and pollute WoW's global space.. Which can lead to breaking your own addon if other people leak globals as well. If you need some help sorting it out hit up the Tukui, WoWUIDev or WoW AddOns discords.

**Comment by solagegrey** [comment]
Thank you for the comment. I would like to make my addon a better citizen of the ElvUI community. Could you provide a specific example, please, that you have observed happening as a result of this addon?

**Comment by Azilroka** [comment]
All the color constants at the top.. you are also globalling E, L, V, P, G. Several functions are global.

**Comment by solagegrey** [comment]
Thank you, I will correct that asap

**Comment by solagegrey** [comment]
I've uploaded a new version - please verify the changes are appropriate and re-open if not satisfied. Thanks again
